# Customise
customize:
    logo:
        enabled: true
        width: 160
        height: 40
        url: images/logo.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: css/images/avatar.png
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: Redbrick
        author_title: DCU's Networking Society
        location: Clubs and Societies Office, Dublin City University, Glasnevin, Dublin 9.
        follow: https://twitter.com/redbrickdcu
    highlight: monokai
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links:
        github: https://github.com/redbrick
        twitter: https://twitter.com/redbrickdcu
        facebook: https://facebook.com/dcuredbrick
        youtube: https://www.youtube.com/user/redbrickdcu
        rss: /atom.xml
        heartbeat: https://redbrick.status.io/
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - tagcloud

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    on: false
    disqus: # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    google_analytics: UA-85359173-1 # enter the tracking ID for your Google Analytics
    google_site_verification: 2WCaCH2N-gzzIIiMIq9ERmtz7cprYKIIPKHoBjzPQYk # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key
    google_recaptcha: 6LdCuwgUAAAAAKB3yf7AcOpyHxIFKJNaH3cNhmEC
    google_cal_api: AIzaSyAV0PnlM4b3k2NoBPglIuMD8vfQwlD31zY
    google_cal_id: r2l6edh5l8jm5t9dbfi84rn26s

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id: RedbrickDCU
        google_plus:
